### ISSUE TITLE
Phase to Phase Voltages

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-api-common#135]
### What's needed?

Some electrical consumers draw energy between two phases or from all three phases. At the moment the phase to phase voltage is missing in the metric enum.

**Comment by llucax** [comment]
> Some electrical draw energy between to phases.

This seems a bit confusing...

Maybe "Some electrical *devices* draw energy between *~to~ two* phases."?

**Comment by tiyash-basu-frequenz** [comment]
This will be a breaking change because adding phase-to-phase voltages means that we need to specify the existing metrics as phase-to-neutral, which is not the case now.

**Comment by tiyash-basu-frequenz** [comment]
In case of single-phase systems, what happens to the phase-to-phase voltages? I need to check.
