### ISSUE TITLE
Inconsistent time stamp usage in sample definitions

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-api-common#141]
### What's needed?

A sample of a time series is defined by a timestamp and a value (see https://github.com/frequenz-floss/frequenz-sdk-python/blob/v1.x.x/docs/user-guide/glossary.md#sample). The current implementations of `SimpleMetricSample`,  `AggregatedMetricSample` and `MetricSampleVariant` do not contain the timestamp, but `MetricSample` does. 

### Proposed solution

Propose to add a timestamp to the base sample types and remove it from `MetricSample` since it uses the others (would also affect coupling to bounds though).

### Use cases

Base sample types like `SimpleMetricSample` and `MetricSample` are both intended to be used by other APIs like reporting API.

### Alternatives and workarounds

Rename Sample types without timestamp to `Value`.

### Additional context

See discussion in https://github.com/frequenz-floss/frequenz-api-reporting/pull/6/files#r1406773110

**Comment by thomas-nicolai-frequenz** [comment]
>Base sample types like SimpleMetricSample and MetricSample are both intended to be used by other APIs like reporting API.

There is no such thing as a `MetricSample` message in the API spec. Can you please clarify @cwasicki

**Comment by thomas-nicolai-frequenz** [comment]
> Base sample types like SimpleMetricSample and MetricSample

@cwasicki I'm not sure I follow. There is `SimpleMetricSample` and `AggregatedMetricSample` but there is no `MetricSample`.

```Protobuf
message MetricSampleVariant {
  oneof metric_return_type {
    SimpleMetricSample simple_metric = 1;
    AggregatedMetricSample aggregated_metric = 2;
  }
}
```

> Propose to add a timestamp to the base sample types

What are a `base sample types`?

**Comment by thomas-nicolai-frequenz** [comment]
> Propose to add a timestamp to the base sample types and remove it from MetricSample since it uses the others (would also affect coupling to bounds though).

Can you explain why we should be doing that? We just moved the timestamp out of `SimpleMetricSample` and `AggregatedMetricSample` for various reasons. 

Additionally you are correct it would break the coupling with `bounds` which now would also need to include the timestamp which would be the same and hence we would repeat timestamps.

**Comment by tiyash-basu-frequenz** [comment]
I'd vote for renaming. To me it is more of an inconsistent naming than inconsistent usage of timestamps (I think the timestamps are spot-on, #FamousLastWords).

**Comment by cwasicki** [comment]
I am fine with renaming to avoid confusion, some suggestions depending on whether it should describe the data or the purpose:
* `SimpleMetricSample` is just a single float value, no timestamp and does not contain a metric type -> 
  * `Value` 
  * `MetricValue`
* `AggregatedMetricSample` is one mandatory and some optional float values ->
  * `ValueAggregate` / `AggregatedValues`
  * `AggregatedMetricValues`
* `SimpleAggregatedMetricSample` is a timestamp and float, i.e. the definition of a sample -> 
  * `Sample`  
  * `Aggregated(Component)Sample`
