### ISSUE TITLE
Metric field not required in MetricSample

### ISSUE THREAD

**Issue by cwasicki** [frequenz-floss/frequenz-api-common#142]
### What's needed?

With metric not being part of `MetricSample`, we can save sending the redundant `metric` data field. This could have a significant impact if large amounts samples are queried. For a simple request of a single metric and no bounds or states instead of 
```
sampled_at, metric, value
``` 
for each single timestamp only 
```
sampled_at, value
```
would be sent.

### Proposed solution

One way to achieve this would be to remove the `metric` field from `MetricSample` and introduce a new type `MetricsList` (could also be nested into `ComponentData`) https://github.com/frequenz-floss/frequenz-api-common/blob/4af9f37e9cfd0a2bc99f0822a2cd2cbc74f48c7b/proto/frequenz/api/common/v1/microgrid/components/components.proto#L221 

```proto

message MetricsList {
   // The metric that was sampled.
   Metric metric = 1;
     
   // List of measurements for a metric of the specific microgrid component.
   repeated frequenz.api.common.v1.metrics.MetricSample samples = 2;     
}


message ComponentData {
  // The ID of the microgrid component.
  uint64 component_id = 1;

  // List of measurements for a metric of the specific microgrid component.
  repeated MetricsList metric_samples = 2;

  // List of states of a specific microgrid component.
  repeated ComponentState states = 3;
}
```

The result should be

```
//             metric_samples: [
//               /* list of metrics for multiple timestamps */
//               { 
//                   metric: "DC_VOLTAGE_V",
//                   samples: [
//                       { sampled_at: "2023-10-01T00:00:00Z", sample: {...}, bounds: {...} },
//                       { sampled_at: "2023-10-01T00:05:00Z", sample: {...}, bounds: {...} },
//                       ...
//                   ]
//               },
//               {
//                   metric:  "DC_CURRENT_A",
//                   samples: [
//                      { sampled_at: "2023-10-01T00:00:00Z", sample: {...}, bounds: {...} },
//                      { sampled_at: "2023-10-01T00:05:00Z", sample: {...}, bounds: {...} },
//                      ...
//              }
//            ],
```
### Use cases

Predominantly data reduction since for a time series the metric would only be sent once instead of being sent with every single sample data point.

### Additional context

Related to https://github.com/frequenz-floss/frequenz-api-reporting/pull/6/files#r1406832835

Could be influenced by https://github.com/frequenz-floss/frequenz-api-common/issues/141

**Comment by thomas-nicolai-frequenz** [comment]
This proposal would introduce more overhead on data stream as each metric will always have just one timestamp. It will introduce an additional nesting in this case. Moreover submitting the metric type multiple times is not so inefficient as protobuf is a binary format and in the cloud data limitations aren't that important in comparison to sending data over mobile connections. We also looked at this alternative but decided against it.

**Comment by thomas-nicolai-frequenz** [comment]
However, one of the advantages could be to be able to more easily introduce a connection identifier for certain metrics like DC_VOLTAGE_V for example as there might be multiple DC strings.

**Comment by tiyash-basu-frequenz** [comment]
>This proposal would introduce more overhead on data stream as each metric will always have just one timestamp. It will introduce an additional nesting in this case.

Agree.

>However, one of the advantages could be to be able to more easily introduce a connection identifier for certain metrics like DC_VOLTAGE_V for example as there might be multiple DC strings.

This won't be of much help though, because there is no guarantee that the order of, say, 3 `DC_VOLTAGE_V` values will be same across all messages.

**Comment by cwasicki** [comment]
> This proposal would introduce more overhead on data stream as each metric will always have just one timestamp. It will introduce an additional nesting in this case.

Yes, for streaming only a single sample it would introduce 2B because of the nesting IIUC. It would become more efficient as soon as you go beyond 2 samples.

>Moreover submitting the metric type multiple times is not so inefficient as protobuf is a binary format 

But still linearly with the number of samples, right?

**Comment by tiyash-basu-frequenz** [comment]
I'd vote for a flatter structure here, since flattened structures in general a) provide more flexibility and b) lead to simpler code.

Flexibility:
The current structure allows us to go into different directions in the future without making breaking changes. E.g., we can choose to not populate `metric` for requests that ask for only one metric, or add more identifiers without breaking the structure.

Simpler code:
There is another benefit of a flat structure: since the samples will be sorted by time, you can get all metrics at one timestamp in a bunch. This will be a very likely use-case. The current flat structure will provide a usability boost while working with it. In the nested approach, you would need extra code to match timestamps across different metrics, which will take more computational time, plus more code, therefore more chances of bugs.

I understand that there is a trade off in terms of data volume, but this will happen in cloud-APIs, where transferring network packets is not so expensive. I could be wrong, but I feel that the nested approach will likely make our data parsing algorithms more complex, which is more critical than network bandwidth in the cloud case. :)

**Comment by cwasicki** [comment]
These are good arguments, in particular simpler data structures are quite beneficial also from a DS perspective. 

Can we close this then?

**Comment by tiyash-basu-frequenz** [comment]
>Can we close this then?

Yes :)

**Comment by llucax** [comment]
Closing as "not planned" instead, so it is more easily visible that this was actually not accepted/implemented.
