### ISSUE TITLE
Look for an alternative for `googleapis-common-protos-stubs`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-api-common#151]
### What happened?

[googleapis-common-protos-stubs](https://pypi.org/project/googleapis-common-protos-stubs/) is not an official package and we don't know if it is properly maintained.

### What did you expect instead?

We should make sure that the dependencies we use are mature, stable and well maintained.

One option could be to get rid of the dependency for `googleapis` proto files, so we don't need the stubs package.

Another option would be to build our own googleapis stubs, or even the whole proto bindings, so we have control over it.

### Affected part(s)

Build script, CI, dependencies, etc. (part:tooling), The python bindings (part:python)

### Extra information

* Snyk info: https://snyk.io/advisor/python/googleapis-common-protos-stubs
* Origin of this issue: https://github.com/frequenz-floss/frequenz-api-common/pull/148#issuecomment-1857712305

**Comment by tiyash-basu-frequenz** [comment]
This issue was addressed in #187 , no?
