### ISSUE TITLE
Depending on `googleapis/googleapis` is overkill

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-api-common#152]
### What happened?

[googleapis/googleapis](https://github.com/googleapis/googleapis) is about 67MiB, and we only use one file, `decimal.proto`, which is just encapsulating a string.

### What did you expect instead?

Having something more lighweight, like our own decimal message.

### Affected part(s)

Build script, CI, dependencies, etc. (part:tooling), The protocol buffer definition files (part:protobuf)

### Extra information

*  This probably needs some investigation to see if how different target languages deal with these `Decimal` types, and if we can get away with it. In Python for example it is trivial to construct a [`decimal.Decimal`](https://docs.python.org/3/library/decimal.html#decimal-objects) from the string.

* Origin of this issue: https://github.com/frequenz-floss/frequenz-api-common/pull/148#issuecomment-1857712305

**Comment by tiyash-basu-frequenz** [comment]
Given our objective is precision and not indefinite lengths, I wonder what benefits we get from using a string for decimal notation. Perhaps we could go for a numeric definition like the following:

```proto
message Decimal {
    sint32 mantissa = 1;
    sint32 exponent = 2;
};
```

**Comment by llucax** [comment]
Yeah, not sure if staying "binary compatible" with google's implementation might bring some value in the future. In any case I think any solution should be better than pulling the whole google proto stuff just for one or two types.

**Comment by Marenz** [comment]
You're not exactly becoming binary incompatible if you use the message tiyash described, it still is, fundamentally, protobuf :)

I would maybe give it a different name though

**Comment by llucax** [comment]
Yeah, I mean that people seeing `Decimal` might expect a different message, this is why it was in quotes, so you didn't take it literally :unamused: :trollface:

**Comment by llucax** [comment]
I was just thinking on a better structure for repos, and the fact that we have this dependency makes things a bit more complicated too. The thing is, types from this repo don't have a good conversion to native language types.

We are [currently only using](https://github.com/search?q=org%3Afrequenz-floss+language%3A%22Protocol+Buffer%22+%22google.type%22&type=code) `google.type.Decimal`. We are using `google.protobuf.Timestamp`, `google.protobuf.Struct`, `google.protobuf.Any`, `google.protobuf.FieldMask` and `google.protobuf.Empty` but everything in `google.protobuf` seems to be part of the `protoc` compiler anyway.

I think I will make a PR to remove the dependency here and just add a `Decimal` type that is the same as Google's, just to make it compatible in case we need the compatibility for some reason. If not just to put more pressure in the discussion :smiling_imp:
