### ISSUE TITLE
Add support to annotate same metrics from different sources for a single component

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-common#172]
### What's needed?

Components can sometimes report the same metric, but from different sensors in different places. E.g., a hybrid inverter can report DC voltage from a battery string and a PV string, or an inverter with multiple DC strings in general.

This is currently not supported in our metric definitions. We have means to define [simple and aggregated metrics samples](https://github.com/frequenz-floss/frequenz-api-common/blob/7997835d103221125258632173cab6de8fd697cd/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L17-L46), and means to [associate metric samples with metric names](https://github.com/frequenz-floss/frequenz-api-common/blob/7997835d103221125258632173cab6de8fd697cd/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L167-L204), but no way of annotating the sensor type (the DC string name, in case inverters have several of these).

We need means to annotate the sensor type somehow, or it would be impossible to encode metric sources in some cases (again in the case of inverters with multiple DC strings).

### Idea 1: Add a new field to `MetricSample` (non-breaking)

We could add a new field to the [`MetricSample`](https://github.com/frequenz-floss/frequenz-api-common/blob/7997835d103221125258632173cab6de8fd697cd/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L167) message, which would contain the additional information about the sensor. Perhaps just an optional string would be fine here.

### Idea 2: Add a new sample variant (non-breaking)

Like `SimpleMetricSample` and `AggregatedMetricSample`, we could add a new message that contains the sensor annotation.

**Comment by tiyash-basu-frequenz** [comment]
@thomas-nicolai-frequenz Do you have any thoughts on this?

**Comment by thomas-nicolai-frequenz** [comment]
I'm not really a fan of idea 2 tbh. It would somehow break the concept of SimpleMetricSample and AggregatedMetricSample. That doesn't mean I do like idea 1 ;-)

**Comment by thomas-nicolai-frequenz** [comment]
So here is the thing. We do already expose "the same metric, but from different sensors in different places" for the three phases. Now putting the dc voltage for solar and dc voltage for a battery on a hybrid inverter into a different place would feel a little inconsistent. I'm not yet suggesting to create something like METRIC_DC_VOLTAGE_SOLAR and METRIC_DC_VOLTAGE_BATTERY but I wanna to share these thoughts to maybe inspire to think about other ways to address the issue in a consistent way.

```
  METRIC_AC_VOLTAGE_PHASE_1 = 12;
  METRIC_AC_VOLTAGE_PHASE_2 = 13;
  METRIC_AC_VOLTAGE_PHASE_3 = 14;
```

Do we have any other requirements beyond the hybrid inverter example above @tiyash-basu-frequenz ?

**Comment by tiyash-basu-frequenz** [comment]
> Do we have any other requirements beyond the hybrid inverter example above

No, we do not. The only case we have encountered so far is multiple DC strings for an inverter.

**Comment by tiyash-basu-frequenz** [comment]
>So here is the thing. We do already expose "the same metric, but from different sensors in different places" for the three phases. 

I think the example you pointed out is not related to what we are trying to address here.

3-phase metrics are standard and consistent. So it is relatively easy to encode these conceptually. E.g., in a 3-phase system, there will _always_ be current and voltage metrics for 3 phases.

What we are trying to address here is encoding metrics coming from arbitrary (non-standard) sensors, and an arbitrary number of sensors (so, not just 3 like we do for 3-phase systems). So, yes, we cannot simply add `METRIC_DC_VOLTAGE_SOLAR` or `METRIC_DC_VOLTAGE_BATTERY`. We also need to
* think of a way to allow adding them multiple times for a component, with arbitrary sensor names, e.g., for the SofarSolar inverter, which has 2 battery strings and 1 PV string.
* think about maintaining association between such metrics consecutive data samples. E.g., if we just use arrays, e.g., `values: [<value for sensor A>, <value for sensor B>, ..]`, there is no inherent guarantee that the sensor corresponding to index 1 in a sample will remain at index 1 in consecutive samples in the data stream.


<details>
  <summary> Some inputs from ChatGPT here </summary>

Handling metrics from arbitrary sensors and ensuring consistent association between consecutive data samples in a scenario where the number and type of sensors are not fixed requires a well-thought-out data structure. Here are some approaches that could be effective:

1. **Sensor Identifier in Metric:** Include a unique sensor identifier within each metric sample. This identifier could be a string or a numeric ID that uniquely represents each sensor. By doing this, each data sample carries its own association with the sensor it came from, ensuring consistency across data streams.

   ```protobuf
   message MetricSample {
       string sensor_id;
       // ... other fields like metric value, timestamp, etc.
   }
   ```

2. **Structured Sensor Data:** Create a nested structure where each sensor has its own data container. This could be a map or a list of sensor-specific data structures. In this way, the data for each sensor is encapsulated within its own structure, maintaining the association between the sensor and its data points.

   ```protobuf
   message SensorData {
       string sensor_id;
       repeated MetricSample metrics;
   }
   ```

3. **Use of Maps for Sensor Data:** Utilize a map structure where the key is the sensor identifier, and the value is the metric data. This ensures that the data for each sensor is always accessed using the same key, preserving the association.

   ```protobuf
   message MetricsData {
       map<string, MetricSample> sensor_metrics;
   }
   ```

4. **Timestamps and Sequence Numbers:** Include timestamps and possibly sequence numbers in each metric sample. This helps maintain the order of samples and can be used to track the sequence of data for each sensor.

5. **Explicit Index Mapping:** If you prefer arrays for efficiency but are concerned about index consistency, consider including an explicit mapping of sensor IDs to array indices as part of your data structure. This mapping can be used to decode the correct sensor for each index in the array.

   ```protobuf
   message MetricsStream {
       repeated string sensor_ids;  // Ordered list of sensor IDs
       repeated MetricSample values; // Values corresponding to the sensor_ids
   }
   ```

6. **Versioning and Integrity Checks:** Implement versioning and integrity checks in your data stream. This ensures that the structure and interpretation of the data are maintained, even if the underlying sensor configuration changes over time.

In the case of the SofarSolar inverter with multiple battery strings and a PV string, each string would have its own unique identifier, and metrics for each string would be associated with these identifiers, ensuring consistency and clarity in your data streams. Remember, the key is to have a robust and flexible system that can handle variability in sensors while maintaining the integrity and association of the data.
</details>

**Comment by thomas-nicolai-frequenz** [comment]
> No, we do not. The only case we have encountered so far is multiple DC strings for an inverter.

Right, so three scenarios:

1. Hybrid inverter with multiple DC solar strings and maybe even multiple DC battery strings.
2. Solar inverter with multiple DC solar strings.
3. Battery inverter with multiple battery strings.

**Comment by thomas-nicolai-frequenz** [comment]
So whats obvious is that we need to be able to attach a metric to some kind of reference / id. Its almost like an attribute. Unfortunately we need to read that ID from the modbus registers and forward that which would require us to forward that as a string as we will not know its composition but we should restrict the length for sure. Is that about correct @tiyash-basu-frequenz ?

**Comment by thomas-nicolai-frequenz** [comment]
I mean the current design already supports multiple entries of the same metric (not intentional), right? So if we add the `string id` to the sample it might be the simplest way forward but I'm not sure if logically the right way to go. I would like to avoid taking a decision because the status quo is the status quo.

**Comment by thomas-nicolai-frequenz** [comment]
This would also impacts the data structure as we have something like **dc_voltage** having multiple children like `string_id_1`, `string_id_2`, ... or just something like `default` if there is just a value.

Exampe 1: Multiple DC strings (future nested approach)
```Json
{
  "ac_voltage": 1,      # <-- the top level fields are ac_voltage and dc_voltage
  "dc_voltage": {
    "233424234": 1,   # <-- first dc string of the inverter
    "898989898": 3    # <-- second dc string of the inverter
   }
}
```

Example 2: One DC string (current)
```Json
{
  "ac_voltage": 1,      # <-- the top level fields are ac_voltage and dc_voltage
  "dc_voltage": 3    # just one string
}
```

No matter if we use the nested structure to store multiple strings or if we just store a plain value we can still implement that on the API side which one we are returning. So when a user requests `dc_voltage` we'd check the type and based upon that either return one or multiple dc_voltage metric samples.

**Comment by tiyash-basu-frequenz** [comment]
@stefan-brus-frequenz, @thomas-nicolai-frequenz, and I discussed it in person, and this is what we came up with:

* We will introduce a new field `optional string tag` to the [`MetricSample`](https://github.com/frequenz-floss/frequenz-api-common/blob/7997835d103221125258632173cab6de8fd697cd/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L167-L204) enum.
* This tag will contain a name or an ID of the sensor/connection, in case there are multiple sensors/connections for a metric in a component (e.g., the DC string in case of hybrid inverters). In the format, this would be represented using hierarchical columns, with one column per tag.
* This tag will not be populated if there is just one sensor (e.g., inverters with one DC string).

**Comment by thomas-nicolai-frequenz** [comment]
We'd also need to extend 

https://github.com/frequenz-floss/frequenz-api-reporting/blob/8be9f966db76b8069b56beb3cb53e637ab4b42a3/proto/frequenz/api/reporting/v1/reporting.proto#L240

**Default**
`{ sampled_at: "2023-10-01T00:00:00Z", metric: "DC_VOLTAGE_V", sample: {...}, bounds: {...} }`

**With Tag**
`{ sampled_at: "2023-10-01T00:00:00Z", tag: "3433534", metric: "DC_VOLTAGE_V", sample: {...}, bounds: {...} }`

**Comment by llucax** [comment]
One question, why naming this generically `tag` and not `source` or something more specific? Do we envision any other metadata we would might like to attach in the future? Wouldn't it make more sense to have some sort of `repeated` key-value metadata field instead in that case?

**Comment by tiyash-basu-frequenz** [comment]
> One question, why naming this generically `tag` and not `source` or something more specific? Do we envision any other metadata we would might like to attach in the future? Wouldn't it make more sense to have some sort of repeated key-value metadata field instead in that case?


_TL;DR:_ `source` sounds good.

`source` may be too specific. We do not intend to populate source all the time. We intend to populate it only in case there are multiple sensors for a metric (as explained in the issue above). So, if a field named `source` is not populated, it could be confusing. That said, we could document this field well enough, and hopefully people read it.

I am not sure if having a generic tag would be worth it. I feel we do not have enough information to make that decision now. All we know now is the requirement mentioned in this issue. If we ever need a generic tag, I'd vote for a Struct (JSON) to keep it flexible and as general-purpose as possible.

**Comment by llucax** [comment]
Sounds good to me, the good thing is that if we need generic metadata in the future it can be easily done a non-breaking change for a long while by just populating both the old `source` and the new metadata struct until we can cleanup the old version.

**Comment by thomas-nicolai-frequenz** [comment]
In fact wether `source` or `tag` doesn't really make a difference. What we are doing is to rely / forward the `identifier` of the "sensor". In the case of multiple DC strings its the `identifier` of each the DC string reporting the eg. DC voltage. This information is used by the user to double check that when e.g. using the inverters web interface for debugging purposes. The question is whether `identifier` or `id` might be better suited but `source` or `tag` are also fine imho. Its just a matter of whats more intuitive.
