### ISSUE TITLE
Represent sensors as as their own category

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-common#51]
### What's needed?

We have two types of equipment in our microgrids:
* electrical control or measurement component, such as inverters, batteries, meters, etc.
* sensors providing details of the surrounding environment, such as temperature, humidity, irradiance, etc.

Currently, [sensors are represented as a component category](https://github.com/frequenz-floss/frequenz-api-common/blob/v0.x.x/proto/frequenz/api/common/components.proto#L37-L38). This breaks the concept of the term "component", which is meant to refer to electrical components only.

Hence, sensors should be represented as an entity disjointed from components. We need to ensure that "sensors", as a concept,
a. exist at the same level as components
b. are not components

### Proposed solution

A simple approach to address this would be to
a. remove sensors from the `ComponentCategory` enum, AND
b. rename the `SensorType` enum to `SensorCategory`.

**Comment by llucax** [comment]
So sensors are not connected to the *component graph* then, right? Are they in any way associated to a particular component or are they *global* to the microgrid?

**Comment by tiyash-basu-frequenz** [comment]
> So sensors are not connected to the _component graph_ then, right?

Correct, _sensors_  have never been present in the component graph, and will not be in the foreseeable future.

> Are they in any way associated to a particular component or are they _global_ to the microgrid?

They may or may not be. Consider the following example:
Imagine if a single microgrid is spread across two different rooms. 2 batteries in room 1, and further 2 batteries in room 2. Room 1 is ventilated, and room 2 is not. Clearly, the temperature and humidity is highly likely to be different for the two rooms. If each room has its own temperature sensor, then the sensors will be naturally associated with the batteries in their respective rooms.

However, this is not what we are trying to address in this issue. Here we just want to separate _sensors_ and electrical _components_, so that it's easy to identify which equipment are a part of a microgrid's electrical circuit, and which are not.

**Comment by thomas-nicolai-frequenz** [comment]
> This breaks the concept of the term "component", which is meant to refer to electrical components only.

We can very precisely define this as in having at least one AC or DC connection. If sensors neither have an AC or DC connection the do not belong to the component category and hence have no place in the component graph. Right now sensors would essentially break the component graph. This is a bug and not a feature @llucax ;-)

When talking sensors we think of irradiation, wind speed or temperature sensors.

> If each room has its own temperature sensor, then the sensors will be naturally associated with the batteries in their respective rooms.

This is really, really tricky. This would add another meta relationship between components and sensors. We have two choices the way I see this:

1. remove sensors from components and component graph
2. keep sensors as a special type in components and in the component graph

If we go for approach 2 and discard the first one I see the following relationships to play out:

1. room temperature/humidity sensors -> battery
2. irradiation sensor -> solar
2. wind speed sensor -> wind turbine

In fact we already have two types of connections in the component graph: AC and DC. We could of course add another one which would be "data connection". To summarise it:

**Connection Type**: We introduce a new connection type called "Data Connection" (or simply "Data") to differentiate it from AC and DC connections. This would represent the data or informational flow from a sensor to a component or vice versa.

**Node Differentiation**: We could have different node types in the component graph. For instance:

Power Components: PV array, inverter, batteries, etc.
Sensors: Irradiation sensor, temperature sensor, etc.

**Comment by thomas-nicolai-frequenz** [comment]
The only case that I could see a bit troublesome would be a general outside temperature sensor as this would related to more general use cases like optimising the aircon. In this case we would want to connect that to what component? Some sensors might be shared by many use cases or components. Of course we can connect it also to multiple predecessor.

**Comment by tiyash-basu-frequenz** [comment]
>This is really, really tricky. This would add another meta relationship between components and sensors. We have two choices the way I see this:
> 1. remove sensors from components and component graph
> 2. keep sensors as a special type in components and in the component graph

How about a 3rd option?
We keep sensors as a separate category, but allow connections to exist between components ans sensors? (ATM a connection can exist only between 2 components)
This provides the conceptual separation we were hoping to get between electrical and non-electrical/non-IT equipment, while providing the association we need.

> In fact we already have two types of connections in the component graph: AC and DC. We could of course add another one which would be "data connection".

I think that association could lead to inconsistencies. The data from a temperature sensor could apply to an inverter and a battery. We could end up publishing the same sensor data from 2 different components. Allowing connections between components ans sensors could help us address this.

**Comment by thomas-nicolai-frequenz** [comment]
OK, another option is to split out sensors and just create external references to power components or power component categories if we want components to just power components. This way we could have two distinct namespaces.
