### ISSUE TITLE
Add country-code to the `Location` message 

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-common#52]
### What's needed?

Some control parameters change depending upon the country of the microgrid. While the country code can be derived from the geo-coordinates, it is better to expose it via our APIs, so that the behaviour of obtaining the codes is more consistent, and clients do not need to worry about it.

### Proposed solution

We need to add the following member to the [`Location`](https://github.com/frequenz-floss/frequenz-api-common/blob/28dcd7c016846514c27b8062392e14f766211e5d/proto/frequenz/api/common/location.proto#L13-L19) message:
```
// Country ISO 3166-1 Alpha 2
string country_code = 3;
```

(from here: https://github.com/frequenz-floss/frequenz-api-microgrid/issues/76#issuecomment-1665920316)

**Comment by Marenz** [comment]
@llucax will that then be available through the SDK?
